// Generated by gencpp from file kelpie/att.msg
// DO NOT EDIT!


#ifndef KELPIE_MESSAGE_ATT_H
#define KELPIE_MESSAGE_ATT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kelpie
{
template <class ContainerAllocator>
struct att_
{
  typedef att_<ContainerAllocator> Type;

  att_()
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
    }
  att_(const ContainerAllocator& _alloc)
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef float _roll_type;
  _roll_type roll;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::kelpie::att_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kelpie::att_<ContainerAllocator> const> ConstPtr;

}; // struct att_

typedef ::kelpie::att_<std::allocator<void> > att;

typedef boost::shared_ptr< ::kelpie::att > attPtr;
typedef boost::shared_ptr< ::kelpie::att const> attConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kelpie::att_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kelpie::att_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kelpie::att_<ContainerAllocator1> & lhs, const ::kelpie::att_<ContainerAllocator2> & rhs)
{
  return lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kelpie::att_<ContainerAllocator1> & lhs, const ::kelpie::att_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kelpie

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kelpie::att_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kelpie::att_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kelpie::att_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kelpie::att_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kelpie::att_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kelpie::att_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kelpie::att_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c66f4de7f99199dd8e863fffbef112ad";
  }

  static const char* value(const ::kelpie::att_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc66f4de7f99199ddULL;
  static const uint64_t static_value2 = 0x8e863fffbef112adULL;
};

template<class ContainerAllocator>
struct DataType< ::kelpie::att_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kelpie/att";
  }

  static const char* value(const ::kelpie::att_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kelpie::att_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 roll\n"
"float32 pitch\n"
"float32 yaw\n"
;
  }

  static const char* value(const ::kelpie::att_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kelpie::att_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct att_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kelpie::att_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kelpie::att_<ContainerAllocator>& v)
  {
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KELPIE_MESSAGE_ATT_H
