// Generated by gencpp from file kelpie/xyz_float32.msg
// DO NOT EDIT!


#ifndef KELPIE_MESSAGE_XYZ_FLOAT32_H
#define KELPIE_MESSAGE_XYZ_FLOAT32_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kelpie
{
template <class ContainerAllocator>
struct xyz_float32_
{
  typedef xyz_float32_<ContainerAllocator> Type;

  xyz_float32_()
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  xyz_float32_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::kelpie::xyz_float32_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kelpie::xyz_float32_<ContainerAllocator> const> ConstPtr;

}; // struct xyz_float32_

typedef ::kelpie::xyz_float32_<std::allocator<void> > xyz_float32;

typedef boost::shared_ptr< ::kelpie::xyz_float32 > xyz_float32Ptr;
typedef boost::shared_ptr< ::kelpie::xyz_float32 const> xyz_float32ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kelpie::xyz_float32_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kelpie::xyz_float32_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kelpie::xyz_float32_<ContainerAllocator1> & lhs, const ::kelpie::xyz_float32_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kelpie::xyz_float32_<ContainerAllocator1> & lhs, const ::kelpie::xyz_float32_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kelpie

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kelpie::xyz_float32_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kelpie::xyz_float32_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kelpie::xyz_float32_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kelpie::xyz_float32_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kelpie::xyz_float32_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kelpie::xyz_float32_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kelpie::xyz_float32_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc153912f1453b708d221682bc23d9ac";
  }

  static const char* value(const ::kelpie::xyz_float32_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc153912f1453b70ULL;
  static const uint64_t static_value2 = 0x8d221682bc23d9acULL;
};

template<class ContainerAllocator>
struct DataType< ::kelpie::xyz_float32_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kelpie/xyz_float32";
  }

  static const char* value(const ::kelpie::xyz_float32_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kelpie::xyz_float32_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::kelpie::xyz_float32_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kelpie::xyz_float32_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct xyz_float32_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kelpie::xyz_float32_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kelpie::xyz_float32_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KELPIE_MESSAGE_XYZ_FLOAT32_H
